-- Migration status: Current / additive.
-- Introduces: daily persisted streak leaderboard snapshots.
-- Current guidance: streak snapshots are generated by backend TypeScript so they
--   can use the same streak-freeze policy as personal Progress. The privileged
--   database functions below provide only the cross-user reads and atomic writes
--   the scheduled backend job needs while keeping normal request RLS policies intact.

CREATE TABLE IF NOT EXISTS community.streak_leaderboard_snapshots (
  snapshot_id    UUID        PRIMARY KEY,
  metric_version TEXT        NOT NULL,
  as_of_utc_date DATE        NOT NULL,
  generated_at   TIMESTAMPTZ NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (metric_version, as_of_utc_date)
);

COMMENT ON TABLE community.streak_leaderboard_snapshots IS
  'One streak leaderboard snapshot header per (metric version, UTC date). Regenerated daily by the 12:00 UTC backend job.';
COMMENT ON COLUMN community.streak_leaderboard_snapshots.as_of_utc_date IS
  'UTC scheduler date the snapshot was generated for. The read API derives next refresh timing separately.';
COMMENT ON COLUMN community.streak_leaderboard_snapshots.generated_at IS
  'Wall-clock time the snapshot job produced this row. Advances on regeneration of the same UTC date.';

CREATE TABLE IF NOT EXISTS community.streak_leaderboard_snapshot_entries (
  snapshot_id        UUID    NOT NULL REFERENCES community.streak_leaderboard_snapshots(snapshot_id) ON DELETE CASCADE,
  public_profile_id  UUID    NOT NULL REFERENCES community.public_profiles(public_profile_id) ON DELETE CASCADE,
  streak_days        INTEGER NOT NULL CHECK (streak_days >= 0),
  base_sort_position INTEGER NOT NULL CHECK (base_sort_position > 0),
  PRIMARY KEY (snapshot_id, public_profile_id)
);

COMMENT ON TABLE community.streak_leaderboard_snapshot_entries IS
  'Tie-neutral base ordering for one streak snapshot. Never stores display names; read APIs derive names from public_profile_id and request locale.';
COMMENT ON COLUMN community.streak_leaderboard_snapshot_entries.streak_days IS
  'Current streak days computed from progress.user_active_review_days using the same freeze policy as personal Progress.';
COMMENT ON COLUMN community.streak_leaderboard_snapshot_entries.base_sort_position IS
  'Deterministic 1-based base ordering by streak_days DESC, public_profile_id ASC. Viewer-specific tie placement is applied by read APIs, not stored here.';

CREATE INDEX IF NOT EXISTS idx_streak_leaderboard_snapshots_metric_as_of
  ON community.streak_leaderboard_snapshots(metric_version, as_of_utc_date DESC);

CREATE INDEX IF NOT EXISTS idx_streak_leaderboard_snapshot_entries_snapshot_rank
  ON community.streak_leaderboard_snapshot_entries(snapshot_id, streak_days DESC, base_sort_position ASC);

ALTER TABLE community.streak_leaderboard_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE community.streak_leaderboard_snapshot_entries ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE community.streak_leaderboard_snapshots TO backend_app;
GRANT SELECT ON TABLE community.streak_leaderboard_snapshot_entries TO backend_app;

DROP POLICY IF EXISTS streak_leaderboard_snapshots_backend_select_runtime
  ON community.streak_leaderboard_snapshots;
CREATE POLICY streak_leaderboard_snapshots_backend_select_runtime
  ON community.streak_leaderboard_snapshots
  FOR SELECT
  TO backend_app
  USING (true);

DROP POLICY IF EXISTS streak_leaderboard_snapshot_entries_backend_select_runtime
  ON community.streak_leaderboard_snapshot_entries;
CREATE POLICY streak_leaderboard_snapshot_entries_backend_select_runtime
  ON community.streak_leaderboard_snapshot_entries
  FOR SELECT
  TO backend_app
  USING (true);

CREATE OR REPLACE FUNCTION community.list_streak_leaderboard_snapshot_participants(
  p_after_public_profile_id UUID,
  p_limit                   INTEGER
)
RETURNS TABLE (
  public_profile_id  UUID,
  user_id            TEXT,
  progress_time_zone TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF p_limit IS NULL OR p_limit < 1 OR p_limit > 1000 THEN
    RAISE EXCEPTION 'p_limit must be between 1 and 1000'
      USING ERRCODE = '22023';
  END IF;

  RETURN QUERY
  SELECT
    profiles.public_profile_id,
    profiles.user_id,
    user_settings.progress_time_zone
  FROM community.public_profiles AS profiles
  INNER JOIN org.user_settings AS user_settings
    ON user_settings.user_id = profiles.user_id
  WHERE profiles.leaderboard_participation_enabled = TRUE
    AND user_settings.progress_time_zone IS NOT NULL
    AND (
      user_settings.email IS NULL
      OR LOWER(btrim(user_settings.email)) NOT LIKE '%@example.com'
    )
    AND (
      p_after_public_profile_id IS NULL
      OR profiles.public_profile_id > p_after_public_profile_id
    )
  ORDER BY profiles.public_profile_id ASC
  LIMIT p_limit;
END;
$$;

REVOKE ALL ON FUNCTION community.list_streak_leaderboard_snapshot_participants(UUID, INTEGER) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION community.list_streak_leaderboard_snapshot_participants(UUID, INTEGER) TO backend_app;

COMMENT ON FUNCTION community.list_streak_leaderboard_snapshot_participants(UUID, INTEGER) IS
  'Pages opted-in non-demo public profiles with a known Progress timezone for the scheduled streak leaderboard snapshot job, including unlinked guests.';

CREATE OR REPLACE FUNCTION community.list_streak_leaderboard_snapshot_active_days(
  p_user_ids TEXT[]
)
RETURNS TABLE (
  reviewed_by_user_id TEXT,
  local_date          TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF p_user_ids IS NULL THEN
    RAISE EXCEPTION 'p_user_ids is required'
      USING ERRCODE = '22023';
  END IF;

  RETURN QUERY
  SELECT
    active_days.reviewed_by_user_id,
    to_char(active_days.local_date, 'YYYY-MM-DD') AS local_date
  FROM progress.user_active_review_days AS active_days
  WHERE active_days.reviewed_by_user_id = ANY(p_user_ids)
  ORDER BY active_days.reviewed_by_user_id ASC, active_days.local_date ASC;
END;
$$;

REVOKE ALL ON FUNCTION community.list_streak_leaderboard_snapshot_active_days(TEXT[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION community.list_streak_leaderboard_snapshot_active_days(TEXT[]) TO backend_app;

COMMENT ON FUNCTION community.list_streak_leaderboard_snapshot_active_days(TEXT[]) IS
  'Loads materialized active review local dates for one scheduled streak snapshot participant page.';

CREATE OR REPLACE FUNCTION community.upsert_streak_leaderboard_snapshot(
  p_metric_version TEXT,
  p_as_of_utc_date DATE,
  p_generated_at   TIMESTAMPTZ
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_snapshot_id UUID;
BEGIN
  INSERT INTO community.streak_leaderboard_snapshots AS snapshots (
    snapshot_id,
    metric_version,
    as_of_utc_date,
    generated_at
  )
  VALUES (
    gen_random_uuid(),
    p_metric_version,
    p_as_of_utc_date,
    p_generated_at
  )
  ON CONFLICT (metric_version, as_of_utc_date)
  DO UPDATE SET generated_at = EXCLUDED.generated_at
  RETURNING snapshots.snapshot_id INTO v_snapshot_id;

  RETURN v_snapshot_id;
END;
$$;

REVOKE ALL ON FUNCTION community.upsert_streak_leaderboard_snapshot(TEXT, DATE, TIMESTAMPTZ) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION community.upsert_streak_leaderboard_snapshot(TEXT, DATE, TIMESTAMPTZ) TO backend_app;

COMMENT ON FUNCTION community.upsert_streak_leaderboard_snapshot(TEXT, DATE, TIMESTAMPTZ) IS
  'Upserts one streak leaderboard snapshot header by (metric_version, as_of_utc_date) and returns its snapshot_id.';

CREATE OR REPLACE FUNCTION community.replace_streak_leaderboard_snapshot_entries(
  p_snapshot_id          UUID,
  p_public_profile_ids   UUID[],
  p_streak_days          INTEGER[],
  p_base_sort_positions  INTEGER[]
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_profile_count  INTEGER;
  v_streak_count   INTEGER;
  v_position_count INTEGER;
  v_inserted_count INTEGER;
BEGIN
  IF p_snapshot_id IS NULL THEN
    RAISE EXCEPTION 'p_snapshot_id is required'
      USING ERRCODE = '22023';
  END IF;
  IF p_public_profile_ids IS NULL OR p_streak_days IS NULL OR p_base_sort_positions IS NULL THEN
    RAISE EXCEPTION 'entry arrays are required'
      USING ERRCODE = '22023';
  END IF;

  v_profile_count := COALESCE(array_length(p_public_profile_ids, 1), 0);
  v_streak_count := COALESCE(array_length(p_streak_days, 1), 0);
  v_position_count := COALESCE(array_length(p_base_sort_positions, 1), 0);

  IF v_profile_count <> v_streak_count OR v_profile_count <> v_position_count THEN
    RAISE EXCEPTION 'entry arrays must have matching lengths: public_profile_ids=%, streak_days=%, base_sort_positions=%',
      v_profile_count,
      v_streak_count,
      v_position_count
      USING ERRCODE = '22023';
  END IF;

  DELETE FROM community.streak_leaderboard_snapshot_entries
  WHERE snapshot_id = p_snapshot_id;

  INSERT INTO community.streak_leaderboard_snapshot_entries (
    snapshot_id,
    public_profile_id,
    streak_days,
    base_sort_position
  )
  SELECT
    p_snapshot_id,
    entries.public_profile_id,
    entries.streak_days,
    entries.base_sort_position
  FROM unnest(
    p_public_profile_ids,
    p_streak_days,
    p_base_sort_positions
  ) AS entries(public_profile_id, streak_days, base_sort_position)
  ORDER BY entries.base_sort_position ASC;

  GET DIAGNOSTICS v_inserted_count = ROW_COUNT;
  RETURN v_inserted_count;
END;
$$;

REVOKE ALL ON FUNCTION community.replace_streak_leaderboard_snapshot_entries(UUID, UUID[], INTEGER[], INTEGER[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION community.replace_streak_leaderboard_snapshot_entries(UUID, UUID[], INTEGER[], INTEGER[]) TO backend_app;

COMMENT ON FUNCTION community.replace_streak_leaderboard_snapshot_entries(UUID, UUID[], INTEGER[], INTEGER[]) IS
  'Atomically replaces all entries for one streak leaderboard snapshot after TypeScript computes streak days and tie-neutral base ordering.';
